changelog:
  categories:
    - title: Features
      labels:
        - enhancement
    - title: Fixes
      labels:
        - bug
    - title: Security
      labels:
        - security
    - title: Documentation
      labels:
        - documentation
    - title: Other Changes
      labels:
        - "*"
